.\" Manpage for tinshell.
.\" Contact mozdrent@gmail.com.in to correct errors or typos.
.TH man 8 "27 July 2021" "devduild_alpha_0.0.1" "tinshell man page"
.SH NAME
tinshell \- a fast and basic shell.
.SH SYNOPSIS
tinshell
.SH DESCRIPTION
tinshell is a fast and basic shell written in C. The project is in alpha stage.
.SH OPTIONS
tinshell does not take any options.
.SH SEE ALSO
https://github.com/BeanGreen247/tinshell
.SH BUGS
.SH AUTHOR
Thomas Mozdren (mozdrent@gmail.com)
